# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce92e051b5b3bd5d9c6ce8b4eef91007046dcc0b3b8ea48fd7fd700a44285f95687243f42f81c6d9cb022a01cca983d9fa2be323b5d94d7dc141ef50edc4f725

test:
  secret_key_base: f28ba52ffa16d624596c7bb5370c32da00fbbe1a1e6701a6cde3f14c7d3f8eb41f0a65bc1e40767241d4cbf2a6e910e6e3600c18a100dad0f22cec42ca0e8e70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
